keywords: Hexo,HTML,CSS,JavaScript,CloudJay
author: Jay,362359635@qq.com
description: 做一个爱游戏爱生活的前端程序猿.
avatar: http://ww1.sinaimg.cn/thumbnail/45f387ebgy1fcz7980walj20xc0tb7bi

twitter:
rss:
weibo:
instagram:

# Comment
duoshuo: cloudjay
disqus:

# Analytics
baidutongji: 93cbe2c7c0e4e50f9857981ad68ffbb2
